#pragma once
//ゲーム中で利用するシーンを列挙する
enum class SceneType {
	SCENE_TITLE,
	SCENE_LOADING,
	SCENE_TUTORIAL,
	SCENE_MODESELECT,
	SCENE_SHOOTING_PLAY,
	SCENE_ACTION_PLAY,
	SCENE_GAMEOVER,
	SCENE_CLEAR,
	SCENE_CREDIT,
	SCENE_EXIT,//ダミーシーン
	
};