#pragma once
//ボタンクラスをインクルードするため

#include "InputInfo/ButtonA/ButtonA.h"
#include "InputInfo/ButtonAll/ButtonAll.h"
#include "InputInfo/ButtonB/ButtonB.h"
#include "InputInfo/ButtonL3/ButtonL3.h"
#include "InputInfo/ButtonLB/ButtonLB.h"
#include "InputInfo/ButtonOption/ButtonOption.h"
#include "InputInfo/ButtonR3/ButtonR3.h"
#include "InputInfo/ButtonRB/ButtonRB.h"
#include "InputInfo/ButtonStart/ButtonStart.h"
#include "InputInfo/ButtonX/ButtonX.h"
#include "InputInfo/ButtonY/ButtonY.h"
#include "InputInfo/ButtonDown/ButtonDown.h"
#include "InputInfo/ButtonUp/ButtonUp.h"
#include "InputInfo/ButtonLeft/ButtonLeft.h"
#include "InputInfo/ButtonRight/ButtonRight.h"
#include "InputInfo/LeftStick/LeftStick.h"
#include "InputInfo/RightStick/RightStick.h"
#include "InputInfo/DPad/DPad.h"